services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=tessera'
      - 'POSTGRES_USER=tessera'
      - 'POSTGRES_PASSWORD=tessera'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tessera']
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=tessera'
      - 'RABBITMQ_DEFAULT_PASS=tessera'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
